spring:
  profiles:
    active: sit
  datasource:
    url: jdbc:mysql://localhost:3306/tiancms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 8080
  jetty:
      acceptors: 2
      selectors: 4
  tomcat:
    min-spare-threads: 20
    max-threads: 100
  connection-timeout: 5000

logging:
  level:
    cn.kiloword.tiancms.dao: debug
    cn.kiloword.tiancms.mapper: debug
    cn.kiloword.tiancms.mbg.mapper: debug
    org.springframework.security: info

mybatis:
  mapper-locations:
    - classpath:cn/kiloword/tiancms/mbg/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 60 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头